### ISSUE TITLE
Ignore blank tokens?

### ISSUE THREAD

**Issue by NilesDev** [omnivector-solutions/jobbergate#105]
A user ended up with an empty token file in ~/.local/share/jobbergate/token
As a result, the jobbergate command did nothing. No error message unless the -v flag was set, just back to the prompt with no visible effect.

The blank token was several hours old, so the content check takes prio over the token's age check.
Suggestion: treat blank tokens as if there's no token.

(Low prio, since it will probably be very rare.)

**Comment by dusktreader** [comment]
Thanks for letting us know about this. We'll address the issue on two fronts:
* Make sure we have a good message for the user in this case
* Cleanup blank tokens (prompt user to log in again)
