### ISSUE TITLE
update-application functionality

### ISSUE THREAD

**Issue by NilesDev** [omnivector-solutions/jobbergate#120]
--update-identifier option: will take priority and prevent any other changes from happening. Is this intended? May want to add that to description of the option.

When not using --update-identifier: only the description seems to be updated. Templates/.py/.yaml files seem to be .tar'd up and sent with the "client.put()" line, but files on the server aren't updated.

**Comment by fschuch** [comment]
Thanks for reporting the issue. We will investigate and discuss the best approach for this:

* better describe this option;
* otherwise fix the issue preventing any other changes from happening.

**Comment by fschuch** [comment]
A task was created to cover this issue: [ARMADA-636](https://app.clickup.com/t/18022949/ARMADA-636).
