### ISSUE TITLE
Missing cluster-agent dependency 

### ISSUE THREAD

**Issue by speglich** [omnivector-solutions/jobbergate#244]
Docker compose expects a `cluster-agent` service not delivered with `jobbergate` project. 

```Dockerfile
  cluster-agent:
    build:
      context: ../../cluster-agent/
      dockerfile: Dockerfile.dev
```
**Impact**

Without this project the docker compose will fail if the user not recognize the cluster-agent dependency. 
 
**Solution**

As described in the docker compose file: 

```Dockerfile
# When the jobbergate-agent is completed, it will be included here and not rely on a
# relative path outside of the jobbergate git repo
```

**Possible workaround**

The cluster-agent is available [here](https://github.com/omnivector-solutions/cluster-agent). 

Clone and move to the same directory containing jobbergate project

**Comment by dusktreader** [comment]
We have moved the agent logic into a new Jobbergate specific component named jobbergate-agent.

**Comment by dusktreader** [comment]
Closing issue.
