### ISSUE TITLE
Error on slurmctld when running docker compose

### ISSUE THREAD

**Issue by luihabl** [omnivector-solutions/jobbergate#248]
When running `docker compose` in [jobbergate-composed](https://github.com/omnivector-solutions/jobbergate/tree/main/jobbergate-composed), the project is not served correctly. It appears to be related with an error on the slurmctld service.  Here is the log from the service showing the error:

```
slurmctld                                  | -- slurmdbd is now active ...
slurmctld                                  | ---> Starting the Slurm Controller Daemon (slurmctld) ...
slurmctld                                  | slurmctld: error: Ignoring obsolete FastSchedule=1 option. Please remove from your configuration.
slurmctld                                  | slurmctld: debug:  slurmctld log levels: stderr=debug2 logfile=debug2 syslog=quiet
slurmctld                                  | slurmctld: debug:  Log file re-opened
slurmctld                                  | slurmctld: error: High latency for 1000 calls to gettimeofday(): 4597 microseconds
slurmctld                                  | slurmctld: Not running as root. Can't drop supplementary groups
slurmctld                                  | slurmctld: debug:  creating clustername file: /var/lib/slurmd/clustername
slurmctld                                  | slurmctld: error: Configured MailProg is invalid
slurmctld                                  | slurmctld: debug:  slurmscriptd: Got ack from slurmctld
slurmctld                                  | slurmctld: debug:  slurmctld: slurmscriptd fork()'d and initialized.
slurmctld                                  | slurmctld: debug:  _slurmctld_listener_thread: started listening to slurmscriptd
slurmctld                                  | slurmctld: debug:  Initialization successful
slurmctld                                  | slurmctld: slurmctld version 23.11.0-0rc1 started on cluster linux
slurmctld                                  | slurmctld: debug:  _slurmscriptd_mainloop: started
slurmctld                                  | slurmctld: cred/munge: init: Munge credential signature plugin loaded
slurmctld                                  | slurmctld: accounting_storage/slurmdbd: init: Accounting storage SLURMDBD plugin loaded
slurmctld                                  | slurmctld: select/cons_tres: init: select/cons_tres loaded
slurmctld                                  | slurmctld: select/linear: init: Linear node selection plugin loaded with argument 17
slurmctld                                  | slurmctld: select/cray_aries: init: Cray/Aries node selection plugin loaded
slurmctld                                  | slurmctld: fatal: Can't find plugin for select/cons_res
```

Is there a known workaround to execute the compose command correctly to setup the development environment?

**Comment by matheushent** [comment]
Hi @luihabl, thank you for your collaboration.

Can you input your OS information please?

**Comment by luihabl** [comment]
Hi @matheushent,

Thanks for the reply. I have not changed anything in the `Dockerfile` or the `slurm.conf` files, I used the ones  that were in the project. I tried to use both the latest commit from the main branch ([6cfa254](https://github.com/omnivector-solutions/jobbergate/commit/6cfa254e1f822057a2a71f3d5ec244ccfe48c600)) and the release [3.4.3](https://github.com/omnivector-solutions/jobbergate/releases/tag/3.4.3).

I ran docker compose in the following systems and got exactly the same results: 
- macOS 13.2.1 (arm), with the env variable `DOCKER_DEFAULT_PLATFORM=linux/amd64`
- Ubuntu 22.10 (x86_64) 
- Windows 11 22H2 19045 (x86_64) via WSL2 with Ubuntu 22.04 LTS

If you want me to share anyway the files let me know.

**Comment by matheushent** [comment]
@luihabl I have used macOS 13.0.1 (chip M1) without the environment variable and it worked for me. Also, I have tested on Ubuntu 20.04.5 whose CPU architecture is x86_64 and it worked.

I suggest for you to spin up an Ubuntu 20.04 instance using lxd and trying again so we can verify that the system is not interfering.

**Comment by luihabl** [comment]
Hi @matheushent, running `docker compose up --build` inside `jobbergate-composed` without the environment variable on the M1 Mac gives me following error 

```
no matching manifest for linux/arm64/v8 in the manifest list entries
```

which I think is due to docker not being able to find a MySQL image for arm64 (m1). I would be curious about why this does not happen to you. 

I am waiting for the project to build on the lxd instance and I'll come back when it has finished.

One question: `cluster-agent` is not defined explicitly as a dependency of the project, but it's used nonetheless. I am using its latest commit of the main, could the issue be caused by a problem on the specific version of that repo? What version/commit are you using?

**Comment by luihabl** [comment]
@matheushent unfortunately, I got exactly the same error again, even when using cluster-agent 2.2.2. It's really strange, because I even used another x86 machine, and it gives me the same thing. Interestingly, when I try to run the slurm docker project from https://github.com/giovtorres/slurm-docker-cluster, it runs without any issue. 

To reproduce the error you literally need to just clone jobbergate and cluster-agent on the same folder, checkout cluster-agent to 2.2.2, and execute docker compose on jobbergate-composed. I wonder if I am doing anything wrong? By the way, I am always adding `127.0.0.1 keycloak.local` to the hosts file on Mac and ubuntu, if this makes any difference.   

Just to be sure, do you have a clean docker build cache when building the project?
